export const CORPSE_SUBSCRIPTION = "CORPSE_SUBSCRIPTION";
export const PLAYER_LOCATION_SUBSCRIPTION = "PLAYER_LOCATION_SUBSCRIPTION";
export const ROOM_SUBSCRIPTION = "ROOM_SUBSCRIPTION";
export const VOTE_SUBSCRIPTION = "VOTE_SUBSCRIPTION";
